import { chromium } from 'playwright-core';
import { executablePath } from './browser.mjs';
const browser = await chromium.launch({ executablePath });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
const page = await ctx.newPage();
await page.goto('http://localhost:4173/#below', { waitUntil: 'networkidle' });
await page.waitForTimeout(1800);
const svg = page.locator('svg[viewBox="0 0 480 320"]');
await svg.scrollIntoViewIfNeeded();
await page.waitForTimeout(600);
await svg.screenshot({ path: '/tmp/vattenlinjen-shots/clerk-zoom.png' });
await browser.close();
