import { chromium } from 'playwright-core';
import { executablePath } from './browser.mjs';
const browser = await chromium.launch({ executablePath });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://localhost:4173/#below', { waitUntil: 'networkidle' });
await page.waitForTimeout(1500);
const svg = page.locator('svg[viewBox="0 0 480 320"]');
await svg.scrollIntoViewIfNeeded();
await page.waitForTimeout(800);
await svg.screenshot({ path: '/tmp/vattenlinjen-shots/clerk-close.png' });
await browser.close();
